### ISSUE TITLE
official Fedora package

### ISSUE THREAD

**Issue by praiskup** [FrostyX/vim-fugitive-pagure#4]
Don't you want to add official Fedora package?

**Comment by FrostyX** [comment]
I have it on my TODO list for many weeks now.
Yea, I will do it this week. It won't take that much time since the spec file is basically ready
https://copr.fedorainfracloud.org/coprs/frostyx/vim-fugitive-pagure/

**Comment by praiskup** [comment]
On Tuesday, March 24, 2020 3:13:02 PM CET Jakub Kadlčík wrote:
> I have it on my TODO list for many weeks now.
> Yea, I will do it this week. It won't take that much time since the spec file is basically ready
> https://copr.fedorainfracloud.org/coprs/frostyx/vim-fugitive-pagure/

FTR, I filled https://bugzilla.redhat.com/show_bug.cgi?id=1816627 today,
inspired by your package - so we can perhaps do review swap ;)

**Comment by FrostyX** [comment]
Package review: https://bugzilla.redhat.com/show_bug.cgi?id=1816872

**Comment by praiskup** [comment]
I already use `vim-fugitive-pagure-1.2-1.fc32.noarch` from Fedora updates.  Thank you!
