### ISSUE TITLE
Should :Gbrowse <commit_id> work?

### ISSUE THREAD

**Issue by praiskup** [FrostyX/vim-fugitive-pagure#5]
E.g. `:Gbrowse 460eae630` points me to point me to link https://pagure.io/copr/copr/commit/460eae630ef0848ca3f29e620ea53d1c74eafdaa/f/  which doesn't work.

**Comment by FrostyX** [comment]
This is really cool usage, I didn't know that it is possible, thanks!

Can you please try PR #6 if it fixes the issue for you?
