### ISSUE TITLE
Make fugitive work with s.f.o?

### ISSUE THREAD

**Issue by praiskup** [FrostyX/vim-fugitive-pagure#7]
I tried Gbrowse today, and it ended-up with:
`fugitive: No Gbrowse handler installed for 'ssh://praiskup@pkgs.fedoraproject.org/rpms/python-copr-common'`

**Comment by FrostyX** [comment]
Yep, that's because the plugin currently recognizes only these servers:

    def is_pagure(remote):
        domains = ["pagure.io", "src.fedoraproject.org"]
        return any(d in remote for d in domains)

I am going to put also `pkgs.fedoraproject.org` in there and make a release. If you want a workaround until then, you can change your URLs in `.git/config`.

**Comment by FrostyX** [comment]
I created a new release `vim-fugitive-pagure-1.4-1` and pushed updates to bodhi.
